#!/usr/bin/env node

var program = require('commander');
var cloneTemplate = require('./utils/cloneTemplate')
var inputStreamPipe = require('./utils/streamPipe')
var infoMerge = require('./utils/infoMerge')
var installDependencies = require('./utils/installDependencies')

program
  .version('0.0.1', '-v, --version')
  .command('init <dir>')
  .action(function (dir) {
    cloneTemplate(dir)
      
      .then(function () {
        return inputStreamPipe()
      })
      
      .then(function (answers) {
        return infoMerge(answers, process.cwd())
      })
      
      .then(function () {
        return installDependencies(process.cwd(), dir)
      })
      
      .catch(function (err) {
        console.log(err)
      })
  })

program.parse(process.argv);
